services:
  - type: web
    name: mineprofit-backend
    env: node
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_PATH
        value: /tmp/mining.db
      - key: SESSION_SECRET
        generateValue: true
